'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.239
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

<Assembly: Elegant.Ui.CommandSourceAttribute("Hospitality_Solution.ApplicationCommands", "Hospitality_Solution.Hospitality_Solution.ApplicationCommands")> 
Namespace Hospitality_Solution

    ' This class is required for commands suppport.
    ' Do not modify this code inside the editor.

    Public Class ApplicationCommands

    End Class


End Namespace

