'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    'tramite uno strumento quale ResGen o Visual Studio.
    'Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    'con l'opzione /str oppure ricompilare il progetto VS.
    '''<summary>
    '''  Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Hospitality_Solution.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        '''  ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property attach_file() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("attach_file", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Icon simile a (Icona).
        '''</summary>
        Friend ReadOnly Property bar_Ico() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("bar_Ico", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property beep_1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("beep_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property beep_10() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("beep_10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property beep_2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("beep_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property beep_21() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("beep_21", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property beep_25() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("beep_25", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property beep_27() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("beep_27", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property beep_28() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("beep_28", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property beep_3() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("beep_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property beep_30() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("beep_30", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property beep_6() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("beep_6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property beep_9() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("beep_9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property beep_Esci() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("beep_Esci", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property beep_Lista() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("beep_Lista", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property beep_Normale() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("beep_Normale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property beep_Piatti() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("beep_Piatti", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_10() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_11() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_15() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_16() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_16", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_17() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_17", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_19() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_19", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_21() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_21", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_22() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_22", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_23() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_23", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_24() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_24", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_27() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_27", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_28() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_28", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_29() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_29", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_3() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_30() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_30", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_34() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_34", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_35() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_35", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_36() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_36", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_37() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_37", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_38() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_38", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_39() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_39", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_4() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_40() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_40", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_41() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_41", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_42() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_42", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_43() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_43", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_44() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_44", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_45() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_45", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_46() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_46", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_47() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_47", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_48() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_48", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_49() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_49", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property button_50() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("button_50", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CancelApproval_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CancelApproval_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Icon simile a (Icona).
        '''</summary>
        Friend ReadOnly Property chef_Ico() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("chef_Ico", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property clock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Delete_PermissionHH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Delete-PermissionHH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DiscardChanges() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DiscardChanges", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Icon simile a (Icona).
        '''</summary>
        Friend ReadOnly Property Hospitality_Ico() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Hospitality_Ico", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NewContentPage_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NewContentPage_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.IO.UnmanagedMemoryStream simile a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property notifica_Prenotazioni() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("notifica_Prenotazioni", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Splash_screen_ombra_bar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Splash_screen_ombra_bar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Splash_screen_ombra_chef() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Splash_screen_ombra_chef", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Splash_screen_ombra_hospitality() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Splash_screen_ombra_hospitality", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Splash_screen_ombra_sporting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Splash_screen_ombra_sporting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Icon simile a (Icona).
        '''</summary>
        Friend ReadOnly Property sport_Ico() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("sport_Ico", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
